mod 'boxen', '3.0.2', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'homebrew', '1.4.1', :github_tarball => 'boxen/puppet-homebrew'
mod 'repository', '2.2.0', :github_tarball => 'boxen/puppet-repository'
mod 'nginx', '1.4.2', :github_tarball => 'boxen/puppet-nginx'
